spring:
  application:
    name: authn-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:auth_service}
    username: ${DB_USER:auth_user}
    password: ${DB_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true
    locations: ${FLYWAY_LOCATIONS:filesystem:db/migration}
  data:
    redis:
      url: ${REDIS_DATASOURCE_URL:redis://localhost:6379}
  security:
    user:
      name: ecom
      password: ecom
      roles:
        - ADMIN
server:
  port: 8501
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka} # Discovery Server Address
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5 # Heartbeat interval - DO NOT DO THIS IN PRODUCTION
app:
  jwt:
    # Generate a 512-bit (64-byte) random key by command: openssl rand -base64 64
    secret: TwIlWN/981FuI7Y2x+JSGDm15Hj54+U2DDtlr3Ij2Ycke4qpiwI/pQMSGoRlw8Vl8+EiZPw4/aC3HqBhUDWdog==
    expiration-ms: 1800000  # 30 minutes in milliseconds