spring:
  application:
    name: authn-server
  datasource:
    url: jdbc:postgresql://${DB_HOST:auth-db}:${DB_PORT:5432}/${DB_NAME:auth_service}
    username: ${DB_USER:auth_user}
    password: ${DB_PASSWORD:auth_pass}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
    locations: classpath:db/migration
  security:
    user:
      name: ecom
      password: ecom
      roles:
        - ADMIN
server:
  port: 8501
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka} # Discovery Server Address
  instance:
    preferIpAddress: true
    lease-renewal-interval-in-seconds: 5 # Heartbeat interval - DO NOT DO THIS IN PRODUCTION
app:
  jwt:
    secret: "your-256-bit-secret-change-this-to-a-strong-random-value"
    expiration-ms: 86400000 # 24 hours